development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: panda_test
  pool: 5
  username: root
  password: "wj123456"
production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: panda
  pool: 5
  username: root
  password: "wj123456"
