# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ceb89bddd7d3c2a59c0a36f62f7915cc77004a62d36a9d37a7723b87df3f64cae1494ffd0c153d3020c25c68f6b82ce25f4aacce5d00b9b8377cb9b76eeb94b

test:
  secret_key_base: 046118c818beb810984efb313fcaf459b9708f97d432be9aaf64b00232f8231c3d6c2ebbd654d800104aa43e702c2845a4eb56a8af02bd39d4777e6fc77c859f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 046118c818beb810984efb313fcaf459b9708f97d432be9aaf64b00232f8231c3d6c2ebbd654d800104aa43e702c2845a4eb56a8af02bd39d4777e6fc77c85f9
